# ── ATS Gap Severity Engine ─────────────────────────────────────────────────
GAP_SEVERITY_THRESHOLD_CONSERVATIVE: float = 0.3
GAP_SEVERITY_THRESHOLD_BALANCED: float = 0.5
GAP_SEVERITY_THRESHOLD_AGGRESSIVE: float = 0.7
EMBEDDING_MODEL: str = "text-embedding-004"
SIMILARITY_FULL_MATCH: float = 0.82
SIMILARITY_PARTIAL_MATCH: float = 0.60
MIN_JOB_SKILLS_FOR_FIT_ENGINE: int = 2
